api_hash: 263447d31ba648bf87b064a6ec7ef990
api_id: 10662565
chat_id: 
5311403141:AAEOk3jJTP8rYGZJQnDluqfKXbYddcFZ1MI
last_read_message_id: 0
ids_to_retry: []
media_types:
- audio
- photo
- video
- document
- voice
- video_note
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
